import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import Providers from "@providers/index";
import { SideBar1, SideBar2 } from "@components/LayoutComponents/SideBar";
import { useSelectedLayoutSegment } from "next/navigation";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Twitter clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className={""}>
        <Providers>
          <div className="flex max-w-screen-2xl justify-between mx-auto  relative">
            <SideBar1 />
            {children}
            <SideBar2 />
          </div>
        </Providers>
      </body>
    </html>
  );
}
